// Public editor field definitions only; no database or server imports.
export const domainFields: Record<string, string[]> = {
  missions: [
    "sequence",
    "requirements",
    "rewards",
    "unlocks",
    "tips",
    "missables",
  ],
  vehicles: [
    "speed",
    "acceleration",
    "handling",
    "braking",
    "seats",
    "price",
    "obtain",
    "customization",
  ],
  weapons: [
    "damage",
    "range",
    "accuracy",
    "fire_rate",
    "magazine",
    "obtain",
    "requirements",
    "attachments",
  ],
  characters: ["role_description"],
  locations: ["region_id", "x", "y", "requirements"],
  collectibles: ["category_id", "location_id", "sequence"],
  properties: ["price", "location_id", "requirements"],
  businesses: ["location_id", "requirements"],
  activities: ["location_id", "requirements"],
  achievements: ["platform", "points", "requirements"],
  guides: ["reading_minutes"],
  cheats: ["effect", "warning"],
};
