-- An opaque handle for a concealed record.
--
-- "Reveal once" has to name the record it wants, and the obvious handle -- the
-- primary key -- is not always opaque. The CMS mints UUIDs, but the seed and
-- any hand-written record use readable ids, and `demo-after-hours` spells out
-- the title the page is trying not to say. That is exactly the metadata leak
-- the spoiler system exists to prevent, so the handle is separated from the
-- key rather than left to depend on how an id happened to be chosen.
--
-- Generated by the application on insert, NOT by a trigger. A trigger would
-- have to UPDATE `entities` immediately after the INSERT, and `entities` is the
-- content table of an external-content FTS5 index: the update fires
-- `entities_au`, which issues a `delete` against a row the insert trigger may
-- not have indexed yet. SQLite does not define the order of two AFTER INSERT
-- triggers, so that race corrupted the search index outright -- every
-- subsequent query failed with "database disk image is malformed".
-- `tests/content.test.ts` asserts that every seeded record carries a token, so
-- a write path that forgets fails loudly instead of silently shipping a record
-- that cannot be revealed.
ALTER TABLE entities ADD COLUMN reveal_token TEXT;
UPDATE entities SET reveal_token = lower(hex(randomblob(16))) WHERE reveal_token IS NULL;
CREATE UNIQUE INDEX idx_entities_reveal_token ON entities(reveal_token);
